import Head from "next/head";
import Link from "next/link";
export const metadata = {
    title: 'Create  Apppp',
    description: 'Generated by create next app',
  }
  
export default function FirstPost() {
    return <>
   
   
      <section>
      <h1>First Post</h1>
        <Link href='/pages'>go to home</Link>
      </section>
   
      
    </>;
}